# main.yml

# Paramètres généraux
project_name: aerial_image_classification
data_directory: data/
output_directory: output/

# Configuration du modèle
model:
  architecture: resnet50
  pretrained: true
  num_classes: 4
  input_size: 224

# Configuration de l'entraînement
training:
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.001
  optimizer: adam
  scheduler:
    type: step_lr
    step_size: 10
    gamma: 0.1

# Configuration de la validation
validation:
  batch_size: 32
  metric: accuracy

# Configuration de la visualisation
visualization:
  save_plots: true
  plot_interval: 5
